/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import ImageInsert_ImageShow.Insert;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public String getId = "";
    public String getImageName = "";
     String s;
     ResultSet rs;
     String date;
     

     
//     public static void main(String[] args) {
//        
//    }
//     
     
     
     
     
     
    public print(String id) {
          DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
          LocalDateTime now = LocalDateTime.now();  
          date = dtf.format(now); 
          
          
        System.out.println("Constructor");
        getId = id;
        System.out.println(getId);
        initComponents();
    }
    
    
        public class func{
            public ResultSet find(String id) throws SQLException{
                
                   System.out.println("Again"+ id);
                      conn get = new conn();
                     
                     
                     String query = "SELECT * FROM `new_member` WHERE id= `id` ";
                     ResultSet rs = get.s.executeQuery(query);
                
                 if(rs.next()){
                                datePrint.setText(date);
                                members_id.setText(rs.getString(1));
                                name.setText(rs.getString(2));
                                phone.setText(rs.getString(3));
                                email.setText(rs.getString(4));
                                amount.setText(rs.getString(11));
//                              month.setText(rs.getString(2));
                 }
                 
                 
                return rs;

            }
        }
        
        public void showComponent(){
                System.out.println("formComponentShown");
                    // Call func meathoad
                   print.func f = new print.func();
                    try {
                        
                        //  recive func meathoad return query result
                        System.out.println("showComponent id "+ getId);
                        rs = f.find(getId);
        
                    } catch (SQLException ex) {
//                        Logger.getLogger(Insert.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
        
        }
        
        public void prints(){
            showComponent();
            System.out.println("prints");
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                print.print(g2);
                return Printable.PAGE_EXISTS;
            });
            
            
            boolean ok = job.printDialog();
            if(ok){
                try{

                job.print();
                }
                catch (PrinterException ex){
                }
            }
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        members_id = new javax.swing.JLabel();
        Jdob = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name10 = new javax.swing.JLabel();
        name12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jid = new javax.swing.JLabel();
        name13 = new javax.swing.JLabel();
        name14 = new javax.swing.JLabel();
        datePrint = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        name15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        amount1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(440, 10));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        print.setPreferredSize(new java.awt.Dimension(1300, 810));
        print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setText("              Receipt Of Gym Management System");
        print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 980, 60));

        name2.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name2.setText("Name :");
        print.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 30));

        name7.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name7.setText("Email :");
        print.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 90, 30));

        name6.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name6.setText("Amount of payment :");
        print.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 270, 30));

        name.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 200, 30));

        amount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 200, 30));

        email.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 200, 30));

        name9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name9.setText("Tel : +8801879388418");
        print.add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 210, 30));

        members_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(members_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 200, 30));

        Jdob.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Jdob.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------");
        print.add(Jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 1080, 30));

        phone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 200, 30));

        name4.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name4.setText("Phone :");
        print.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 110, 30));

        name10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name10.setText("***************************************");
        print.add(name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 500, 30));

        name12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name12.setText("  Bohoddarhat, Chittagong");
        print.add(name12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 250, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Thank You");
        print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, 190, 40));

        Jid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(Jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 200, 30));

        name13.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name13.setText("ID :");
        print.add(name13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 80, 30));

        name14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name14.setText("************************************************************************************************");
        print.add(name14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 1080, 40));

        datePrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        print.add(datePrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 110, 30));

        name5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name5.setText("Date :");
        print.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 60, 30));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setOpaque(true);
        print.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1590, 1900));

        name8.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name8.setText("Phone");
        print.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 30));

        name15.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        name15.setText("Phone");
        print.add(name15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 30));

        jLabel4.setText("jLabel4");
        print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 210, -1));
        print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 150, 100));

        jLabel5.setText("jLabel5");
        print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));
        print.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        name16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name16.setText("**************************************************************************************");
        print.add(name16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 960, 40));

        jTextField1.setText("jTextField1");
        print.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 710, -1, -1));

        jLabel3.setText("jLabel3");
        print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jTextField2.setText("jTextField2");
        print.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        jTextField3.setText("jTextField3");
        print.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 230, -1));
        print.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, -1, -1));

        amount1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        print.add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 200, 30));

        jLabel6.setText("jLabel6");
        print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel7.setText("jLabel7");
        print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel8.setText("jLabel8");
        print.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jTextField4.setText("jTextField4");
        print.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel9.setText("jLabel9");
        print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        jLabel10.setText("jLabel10");
        print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 300, 30));

        jLabel11.setText("jLabel11");
        print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 220, 40));

        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new print("6666666").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jdob;
    private javax.swing.JLabel Jid;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel amount1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel datePrint;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel members_id;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name10;
    private javax.swing.JLabel name12;
    private javax.swing.JLabel name13;
    private javax.swing.JLabel name14;
    private javax.swing.JLabel name15;
    private javax.swing.JLabel name16;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JLabel phone;
    private javax.swing.JPanel print;
    // End of variables declaration//GEN-END:variables
}
